---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenmail
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: greenmail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: greenmail
    spec:
      containers:
        - name: greenmailserver
          image: greenmail/standalone:2.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: greenmail
spec:
  ports:
    - name: "1465"
      port: 1465
      targetPort: 3465
    - name: "1993"
      port: 1993
      targetPort: 3993
    - name: "1025"
      port: 1025
      targetPort: 3025
    - name: "1110"
      port: 1110
      targetPort: 3110
    - name: "8081"
      port: 8081
      targetPort: 8080
    - name: "1143"
      port: 1143
      targetPort: 3143
  selector:
    app.kubernetes.io/name: greenmail
  type: ClusterIP